"""Generates the PDF snapshot behind api/routers/reports.py.

Kept deliberately separate from the router so the PDF layout can be unit
tested without spinning up the API or a database.
"""
import io
from datetime import datetime
from typing import Any, Dict

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

_STYLES = getSampleStyleSheet()
_TITLE_STYLE = ParagraphStyle("ReportTitle", parent=_STYLES["Title"], fontSize=18, spaceAfter=4)
_SUBTITLE_STYLE = ParagraphStyle("ReportSubtitle", parent=_STYLES["Normal"], textColor=colors.grey, spaceAfter=18)
_SECTION_STYLE = ParagraphStyle("SectionHeader", parent=_STYLES["Heading2"], spaceBefore=16, spaceAfter=8)
_BODY_STYLE = _STYLES["Normal"]
_DISCLAIMER_STYLE = ParagraphStyle("Disclaimer", parent=_STYLES["Normal"], fontSize=8, textColor=colors.grey, spaceBefore=24)


def _kv_table(rows: list[tuple[str, str]]) -> Table:
    table = Table(rows, colWidths=[1.8 * inch, 4.4 * inch])
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#333333")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return table


def _domain_table(domains: list[dict]) -> Table:
    header = ["Domain", "Score", "Key Findings"]
    rows = [header]
    for domain in domains:
        findings = "; ".join(item["text"] for item in domain.get("evidence", []))
        rows.append([domain["name"], f"{domain['score']}/{domain['max']}", Paragraph(findings, _BODY_STYLE)])

    table = Table(rows, colWidths=[1.6 * inch, 0.7 * inch, 3.9 * inch], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a1a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def generate_report_pdf(
    case: Dict[str, Any],
    evidence: Dict[str, Any],
    assessment: Dict[str, Any],
    disposition: str,
    generated_by: str,
    generated_at: datetime,
    report_id: str,
) -> bytes:
    """Renders a single-evidence authenticity report as a PDF and returns
    its raw bytes. `assessment` is the "assessment" sub-object produced by
    api/services/assessment_engine.py's evaluate_assessment (verdict,
    conf, domains, totalScore)."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    story = [
        Paragraph("Veritas Nexus", _TITLE_STYLE),
        Paragraph("Digital Media Authenticity Report", _SUBTITLE_STYLE),
        Paragraph("Case Information", _SECTION_STYLE),
        _kv_table([
            ("Case Number", case["case_number"]),
            ("Title", case["title"]),
            ("Status", case["status"]),
        ]),
        Paragraph("Evidence Information", _SECTION_STYLE),
        _kv_table([
            ("Filename", evidence["filename"]),
            ("SHA-256", evidence["sha256"]),
            ("Uploaded By", evidence["uploaded_by"]),
            ("Uploaded At", evidence["uploaded_at"]),
        ]),
        Paragraph("Authenticity Assessment", _SECTION_STYLE),
        _kv_table([
            ("Verdict", assessment["verdict"]),
            ("Confidence Score", f"{assessment['conf']} / 100"),
            ("Disposition", disposition),
            ("Scoring Policy", assessment["policy"]),
        ]),
        Spacer(1, 12),
        _domain_table(assessment["domains"]),
        Paragraph(
            f"Report ID: {report_id} &nbsp;|&nbsp; Generated by {generated_by} on "
            f"{generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            _DISCLAIMER_STYLE,
        ),
        Paragraph(
            "This report is an automated forensic summary produced by the Veritas Nexus "
            "platform. It is a snapshot of the platform's own analysis at the time of "
            "generation and does not constitute independent expert testimony.",
            _DISCLAIMER_STYLE,
        ),
    ]

    doc.build(story)
    return buffer.getvalue()
